# Generated by Django 3.1.7 on 2021-04-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digital_Diary_app', '0002_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
