# Generated by Django 3.1.7 on 2021-04-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digital_Diary_app', '0003_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
