# Generated by Django 3.1.7 on 2021-04-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digital_Diary_app', '0005_auto_20210419_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
